[build]
  command = "npm ci && npm run build"
  publish = "www"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--prefer-offall --no-audit"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"
  directory = "netlify/functions"
