[build]
  command = "npm install && npm run build --prod"
  publish = "www"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--prefer-offline"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"
  directory = "netlify/functions"
